[package]
name = "planetmap"
version = "0.1.0"
authors = ["Benjamin Saunders <ben.e.saunders@gmail.com>"]
license = "MIT/Apache-2.0"
edition = "2018"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["ash", "simd", "ncollide", "nphysics"]
simd = ["simdeez"]
ncollide = ["ncollide3d", "lru"]
nphysics = ["nphysics3d"]

[dependencies]
na = { package = "nalgebra", version = "0.18" }
slab = "0.4.2"
hashbrown = "0.6"
ash = { version = "0.29", optional = true }
simdeez = { version = "0.6.1", optional = true }
ncollide3d = { version = "0.20", optional = true }
nphysics3d = { version = "0.12.0", optional = true }
lru = { version = "0.1", optional = true }

[dev-dependencies]
winit = "0.18.1"
criterion = "0.2.10"
vk-shader-macros = "0.2"
memoffset = "0.2.1"
half = "1.3.0"
noise = "0.5.1"
fuzzyblue = { git = "https://github.com/Ralith/fuzzyblue", rev = "0f010dbdf7c106bdbea2f7564e31620f2e30447a" }
approx = "0.3.2"

[[bench]]
name = "bench"
harness = false

[[example]]
name = "demo"
required-features = ["ash", "ncollide", "nphysics"]

[target.'cfg(windows)'.dev-dependencies]
winapi = { version = "0.3.4", features = ["windef", "winuser"] }

[target.'cfg(target_os = "macos")'.dev-dependencies]
metal-rs = "0.6"
cocoa = "0.13"
objc = "0.2.2"
